"""init

Revision ID: a40297f18dcc
Revises: 005ce6e94401
Create Date: 2023-04-27 18:59:16.065420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40297f18dcc'
down_revision = '005ce6e94401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
